
# make clean/all CONFIG=Debug/Release ARCH=linux64/raspi ECHO=0/1

# the parrent dir of "arch" dir
ROOT_DIR = ../../../../..

#PROJ_SRCS = $(wildcard *.cpp)
PROJ_SRCS = nbd_comm_test4_iots.cpp

# list of directories containing header files
#PROJ_INC_DIR = $(ROOT_DIR)/include
PROJ_INC_DIR = ../../include ../../../framework/include

# the executable file
PROJ_OUT = main_test.out

# list of ADDITIONAL compiler flags (prepended with "-" sign)
#PROJ_CFLAGS = -Wunused-but-set-variable
PROJ_CFLAGS =
PROJ_CPPFLAGS =-std=c++11

#PROJ_MACROS = _BSD_SOURCE
PROJ_MACROS =

# additional object files (created by other projects)
PROJ_ADD_OBJS = dispatcher.obj request_host.obj thread_pool.obj semaphore.obj select.obj nbd_comm.o transmitter.obj

# additional libraries
PROJ_LIBS =

# linker flags
PROJ_LDFLAGS =

# list of projects (makefiles) this project depends on
PROJ_DEPENDS  =  ../dispatcher/Makefile ../request_host/Makefile ../../../framework/src/function/Makefile ../nbd_comm/Makefile ../../../framework/src/reactor/Makefile ../../../framework/src/thread_pool/Makefile ../../../framework/src/semaphore/Makefile ../../../framework/src/observer/Makefile ../transmitter/Makefile

include $(ROOT_DIR)/make/Project.mak
